### ISSUE TITLE
Replace button to table of Measurements

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio#227]
At object's description page, like that image
![plant](https://user-images.githubusercontent.com/19666564/44096697-49170a54-9fb2-11e8-99f0-2616e01eb5af.png)
we see a button with the number of measurements of this object. I suggest to replace this by a table with columns measurer, date, trait and value; 1 line for each measurement.
Additionally, I suggest to maintain the `Create Measurement` button that appears when the object has no measurement.

**Comment by andrechalom** [comment]
This was done to reduce page load for complex objects, and also because this page would supposedly display some summary of measurements. However, that never got implemented due to the complexity of the measurement interface. I think this is a good idea to have the measurement table in the object page.

**Comment by betovicentini** [comment]
Clicking on the button brings you to the measurement table with the filtered values in the format by @birutaibm. Perhaps in these show.blade of objects, there should be a summary table for measurements:  trait_name, measurements_count, date_range. And we could add, at least for numerical values a link on each line leading to graphical visualizations of values by trait for the object.

**Comment by betovicentini** [comment]
Table removed and button left. Page load resolved
