### ISSUE TITLE
Location table modelling

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio#27]
UCs are like any other polygon based searching that one may need to extract and visualize data from. Therefore, perhaps it should be better to have a (shapefile and kml import tool and diva interaction) and create a tool that allows one to extract data by coordinates falling inside polygons (whose categories are chosen from the shapefile attribute table or kml tags). This said, uc_id my not be needed in the location table if we make mandatory that locations have coordinates.

**Comment by betovicentini** [comment]
OTHER COMMENTS:

"Some marked Plants have a GPS point associated, but otherwise no location registered. These points should be stored as a Location. (ATTENTION!)" - 
I think we don't need to store GPS as locations. This is implemented in duckewiki because of how we have been collecting data in the field (import data from gps device to wiki and link to specimens collected the same days; this has added a lot of non used waypoints in GPS_DATA table). 

We will have data cleaning in R before importation, so we should implement that each object MUST have a lat long associated (the only exception are old herbarium specimens for which locations are uncertain, sometimes only the country is known). 

We could really simplify location. User may just select data dragging onto a map. 
That said, perhaps we should discuss what is really the use location names as currently implemented. Plots and subplots are required. Traditional herbarium locations (gazetteers) could just be stored as a location notes, without normalization, because it is a mess when importing such data from herbarium databases. So, for these, coordinates mandatory and those old specimens without possibility of georeferencing previous to importation (R cleaning tools), then, we just link to the most local administrative info, as these layers are easy to have.  

"Locations are stored in the database as a Polygon, or a series of lat/long points." - perhaps we should restrict to locations that either a polygon (shapefile, kml or coordinate vertices), or are points with lat and long with a dimension associated to it (plots). 

Any object (voucher, plant) not directly associated to a location could just have a lat and long direct reference.
 
"The first of these points to be stored is privileged, as it may be used as a reference for relative markings." -  NAO ENTENDI.

"A plugin may be written for other Location references, such as plants marked with point-quadrant method." - point-quadrant method could be also a location and it could be specified a specific type of location (both point-quadrats and plots). Then we have polygon based (any layer the user may want to import + plus the seeds from DIVA) and point-base locations limited to special locations like plots (transects), point-quadrats and any object (plant, voucher, sample) not associated a location, could just have a mandatory a very specific lat and long reference.

"TODO: plots should have x, y dimension instead of polygons? Sub-plots have start-x, start-y?" 

As discussed above, then star-x and start-y would be a mandatory category of subplots. We also have the possible cases of:  time-search transects; ppbio peld protocols (plots em curva de nivel), que poderiam ser polygonos.

**Comment by andrechalom** [comment]
I've been struggling with these topics. 

I don't think there is a way of having both hierarquical locations and location-based searches, both optional at the same time, and done with efficient queries. Also, the interface for the end user to enter new location data will be a total mess.

- The first alternative is having hierarquical locations, with "Amazonas" being registered as a child of "Brazil". This way, when we try to determine which plants are registered in Brazil, we first expand the tree of Brazil descendants, determine that "Amazonas" is child of "Brazil", and collect all plants whose location is "Brazil or Amazonas or... ". With this modeling, conservation units need a special treatment, since they cannot be fitted in the administrative hierarchy. Here, the spatial search will be done mostly when registering new Locations.

- An alternative would be to remove the hierarquical categorization of Locations, so we could register "Brazil", "Amazonas", and "Estação Ecológica de Bananal", without registering which is "parent" of which, and just perform the queries by selecting plots spatially inside these regions. However, this may be painfully slow for searches such as "how many plants are registered inside Amazonas?". It also presents some challenges. If a voucher is registered as being from "Manaus", should it be displayed when I select any polygon inside Manaus? Or should it be displayed only when I select a polygon that completely covers Manaus?

> I think we don't need to store GPS as locations. This is implemented in duckewiki because of how we have been collecting data in the field (import data from gps device to wiki and link to specimens collected the same days; this has added a lot of non used waypoints in GPS_DATA table).

As I explained over Skype, this is necessary to avoid having several columns to store other data such as GPS datum for these points. It also improves the data modeling in the sense that with GPS points being Locations, each plant MUST have a location. Instead, if plants can have a location OR a GPS point, this will lead to a severe denormalization, affecting also the efficiency of queries such as "Which plants were collected in Amazon", since this query will need to consider all locations PLUS all plants with no location.

> "Locations are stored in the database as a Polygon, or a series of lat/long points." - perhaps we should restrict to locations that either a polygon (shapefile, kml or coordinate vertices), or are points with lat and long with a dimension associated to it (plots).

Locations geometry object must be of GeometryCollection datatype, as it may involve MultyPolygongs (such as when a state is comprised by a continental part + islands). It then must also accept points, and lines (which can be useful for transects). Also, shapefiles and kml may be used for importation, but the actual data that is stored in MySQL is a WKB.

**Comment by betovicentini** [comment]
I think for making queries easier, we should go with option one: keep hierarchy and treat polygon based layers (including UCS as seed data) as a special case. You could also have in the layer based search, the polygons for administrative boundaries and other elements stored in the hierarchy, an it just uses the names of polygons (ids) to query data and only spatial polygon searches when polygon based layers are not in the hierarchy (R can do this quite quickly).
