### ISSUE TITLE
Location start-x and start-y 

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#40]
These fields should only be required if the location's parent is a Plot. On other cases, they should not be stored

**Comment by andrechalom** [comment]
We have several open questions here, derived from the data denormalization of start-x/start-y...

- how to interpret a start-x/start-y from a plot when the parent plot is stored as a Geometry?
- should we allow a user to store a subplot with start-x, start-y if the parent plot is stored as Geometry?
- should we enforce that start-x < parent's x? what happens if the parent is a Geometry?
- should we enforce that x < parent's x? what happens if the parent is a Geometry?
- what happens if the parent plot was stored as lat/long, but later edited and changed to geometry?
- what happens if the parent plot was stored as geometry, but later edited and changed to lat/long?
- a subplot stored with start-x/start-y should have any geometry at all? what happens if a subplot is stored with geometry, and later edited to start-x/start-y? what happens in the reverse case?

**Comment by betovicentini** [comment]
My replies
> - how to interpret a start-x/start-y from a plot when the parent plot is stored as a Geometry?
> - should we allow a user to store a subplot with start-x, start-y if the parent plot is stored as Geometry?
> - should we enforce that start-x < parent's x? what happens if the parent is a Geometry?
> - should we enforce that x < parent's x? what happens if the parent is a Geometry?
If location is a plot it MUST have dim-x and dim-y, so this should not be a problem. Start-x/start-y is the portion of dim-x and dim-y used by the subplot.
> - what happens if the parent plot was stored as lat/long, but later edited and changed to geometry?
> - what happens if the parent plot was stored as geometry, but later edited and changed to lat/long?
As indicated #42 , plots can have either a lat/long or geometry, and require dim-x and dim-y. If user defines a lat/long rather than geometry, then this point coordinate would be referencing the 0,0 of the dimx and dimy (this could be just informed). And when mapping the plot, just assume that dim-x has a West-East orientation and dim-y a North-South from the point with coordinates. 
> - a subplot stored with start-x/start-y should have any geometry at all? what happens if a subplot is stored with geometry, and later edited to start-x/start-y? what happens in the reverse case?
I think subplots could have a geometry+lat/long to the start-x, start-y position. Having a geometry, start-x+dim-x,start-y should match the a vertices, start-y+dim-y, start-x_dim-x another, and so on. Understand conversions between metric and lat-long would not be precise enough if both types of info (lat+long) and geometry, but a simple warning could be issue to the user. 
Anyway, plots and subplots are used with this definitions mostly at CTFS like plots. I think allowing flexibility over this is important and this types of info could be dealt with separately for plots and somewhat independent of each other (geometry and lat/long for plots only).

**Comment by betovicentini** [comment]
1. Start X e Start Y should only appear in the form when parent is a **plot**
2. Parent should appear just below Administrative Level

**Comment by betovicentini** [comment]
About the comment above regarding Parent for Locations:

The "AutoDetect" button below geometry is not obvious what it does and the interface should make that clear. Because it is related to detecting parent the parent. Then it could have the name of "Parent detect" and also an "alt" or help button informing that it will use the geometry/coordinates to detect a parent. Could also show only when geometry or coordinates are filled. Alternatively, place button aside the Parent field, which become more intuitive.

**Comment by andrechalom** [comment]
Implementing this now. I'm keeping start-x and start-y for all plots under a parent plot, checking that start-x/y are non-negative and less than the parent dimension, but no further checking will be made (such as "overlaping subplots")

**Comment by andrechalom** [comment]
Also NOTICE that as some locations are stored as points, and thus are dimensionless, the routine that checks that the new location falls within the parent geometry must be skipped, leading to possible data errors.
