### ISSUE TITLE
Support polygons for "Plot" Locations

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#42]
From @betovicentini 
"We could have a button that shows or hides the selected option (lat/long/x/y versus geometry object) to minimize user confusion. We should keep by default the lat/long/x/y interface, but allow for an optional geometry input"

**Comment by andrechalom** [comment]
This can be done using a "ad hoc" level in the Administrative Levels, such as "Plot (polygon)"

**Comment by betovicentini** [comment]
Currently, the interface does not allow Latitude and Longitude for locations that are polygons, so the options for geometry should consider:
1. Locations that have a geometry (admin levels, UCS), could have a geometry definition **and/or** a latitude, longitude definition (e.g. of its centroid or the capital of the admin level, which is data available). This is important, because object at such location that does not have individual coordinates will derive coordinates from location.
2. Geometry OR lat long should be mandatory.
3. Location seed should have more than Brazil, we should include all Latin America in my opinion as relates to a common flora. 
4. A plot may have both, a latitude and longitude coordinate and a geometry (4 vertices).

**Comment by andrechalom** [comment]
This raises much more problems than it fixes...

>  Locations that have a geometry (admin levels, UCS), could have a geometry definition and/or a latitude, longitude definition
Any kind of and/or data is denormalized. Should we have two different database columns for lat/long and geometry? Do you want to force all your users to check whether a given location has a geometry **or** a lat/long? Should we enforce that the lat/long coordinates are inside the geometry polygon?

> This is important, because object at such location that does not have individual coordinates will derive coordinates from location.
It's easy to retrieve the centroid from any geometry. Any application that wants to access data as lat/long may use the centroids.

**Comment by andrechalom** [comment]
This and #41 must be done with great care not to break the new location duplication detection

**Comment by betovicentini** [comment]
This raises much more problems than it fixes...

>  Locations that have a geometry (admin levels, UCS), could have a geometry definition and/or a latitude, longitude definition
> - Any kind of and/or data is denormalized. Should we have two different database columns for lat/long and geometry? Do you want to force all your users to check whether a given location has a geometry **or** a lat/long? Should we enforce that the lat/long coordinates are inside the geometry polygon?

Locations that have both should give preference (in storage) for Geometry over Lat-Long, because a point coordinate would be part of a bigger geometry. But both fields should be available in some cases to facilitate user input, then validation deals with duplication and stores only one option (may ask or warn user in those cases). I understand that the user may just annotate POINT(x,y)  for a geometry having a single coordinate, but most people will not easily handle the Geometry field (my guess). This is important for plots.

> This is important, because object at such location that does not have individual coordinates will derive coordinates from location.
> - It's easy to retrieve the centroid from any geometry. Any application that wants to access data as lat/long may use the centroids.

Ok, this is great and must be considered in export options.

**Comment by andrechalom** [comment]
If I understand correctly, you're asking for the interface to have always the two options, geom and lat/long, and the system should handle the duplication? I believe this will create a very confusing user interface, isn't there another way?

**Comment by andrechalom** [comment]
More specifially when input data for plots, your comments seem to imply that a plot that's stored as geometry must have dim-x and dim-y declared. That's a data duplication that I would like to avoid, as it introduces margin for error (what happens if the points in the geometry are 4 km apart, but the plot dimension is declared as 100m?)

**Comment by andrechalom** [comment]
I'm waiting for answers here to be able to work on all the location related issues.

**Comment by andrechalom** [comment]
Proceeding in implementation due to lack of activity in this issue. 

- I'm not opening the possibility of introducing simple lat/longs for countries, states, municipalities, etc, as I believe this will beat completely the purpose of the system. The users should be capable enough to enter this kind of data from www.gadm.org. Retrieving the centroid lat/long for complex geometries is already implemented.
- I'm not implementing "A plot may have both, a latitude and longitude coordinate and a geometry", as this would require a major reworking of the data model, which is not attainable at the current project schedule.
- I'm keeping the lat / long data entry as default for plots, but adding a button to enter the full geometry. This is a very large reworking of some parts of the system, as the initial modeling expected that the type of geometry should be obvious from the `$location->adm_level`.
- All plots will be required to have the X/Y dimensions declared, even if they have a geometry. No validation will be done to check the relation between these values.

**Comment by andrechalom** [comment]
Check for possible changes in:
- views (create / show)
- controller / validate
- datatable
- app/Location?
- plant / vouchers

**Comment by andrechalom** [comment]
- Also, I'm removing the check on duplicates from geometry-based plots, as that is much more complex.
