### ISSUE TITLE
Point-quadrant methods should be included in the 1.0 release

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#83]
By @betovicentini request

**Comment by andrechalom** [comment]
Questions for data modeling.

- A single location may have Plants registered with distance/angle and x/y?
- A single plant may have d/a and x/y? What should be displayed if, because of a bug, a plant is registered with both?
- Should there be a switch in the location table to control whether its plants should be d/a or x/y?
- A plot with d/a plants may have child locations with x/y? What about the reverse?
- What should happen to these plant registers if the location is updated?

**Comment by betovicentini** [comment]
> - A single location may have Plants registered with distance/angle and x/y?
> - A single plant may have d/a and x/y? What should be displayed if, because of a bug, a plant is registered with both?
> - Should there be a switch in the location table to control whether its plants should be d/a or x/y?

No, x/y apply only to plants in plots or subplots. Plant liked to a point location (case of point quadrat) should not have x/y, so the option for distance/angle should be made available only if location is a point. So a plant cannot be registered with both.

> - A plot with d/a plants may have child locations with x/y? What about the reverse?

No, there will be no plots in which a plant have d/a data. Plants in plots may have x/y but this is also optional, because most people do not collect this information.

> - What should happen to these plant registers if the location is updated?

A location that have plants on it will require special permission/or validation to be able to change some info like dim-x, dim-y if plants on it have x/y.

**Comment by andrechalom** [comment]
Can you send me some example of data stored as point quadrat? It's being very hard for me to understand how this data will be incorporated.

**Comment by andrechalom** [comment]
I'm still waiting for some sample data, @betovicentini  can you send me a spreadsheet with the type of data the system should handle?

**Comment by andrechalom** [comment]
From what I understood, angle/distance can only be incorporated if the plant's parent is a Point, with plants registered in plots having x/y. However, this can all be stored as the same Geometry object in the database.

So, I'm writing the views to switch "x/y" or "angle/distance" depending on the location selected, and the controller will call the appropriate method depending on the parent location as well. All plants will have x, y, angle and distance accessors. Also,the controller needs special validator functions depending on the data type.

Angles are supposed to be in degrees. The expected behavior can be asserted on the tests/Unit/PointQuadrantTest.php file.
